FROM node:10.16.3

RUN mkdir /code
WORKDIR /code
COPY package.json /code/
RUN yarn install
COPY . /code/
RUN yarn build

ENV HOST 0.0.0.0   # Insensitive environment variable

EXPOSE 3000

#CMD ["yarn", "start"]